routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

$this->group([
              'middleware'  => ['auth'],
              'namespace'   =>  'Admin',
              'prefix'      =>  'admin' 
             ],function() { 


Route::resource('home', 'HomeController');
Route::resource('setores', 'SetorController');
Route::resource('unidades', 'UnidadeController');
Route::resource('horarios', 'HorarioController');


});

app/Models/Admin/Unidade.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use App\Models\Admin\Horario;

class Unidade extends Model
{
    
 protected $fillable = [
        'nome', 'telefone','email','localizacao','horario_id'
    ];


    public function horario(){

        return $this->belongsTo(Horario::class);
      }
	



}

app/Http/Controllers/Admin/UnidadeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin\Unidade;
use App\Models\Admin\Horario;
use App\Http\Requests\UnidadeValidationFormRequest;
use DB;
use Alert;


class UnidadeController extends Controller
{
    public function index()
    {

        $horarios = Horario::get();

        $unidades = DB::table('unidades')
            ->join('horarios', 'unidades.horario_id', '=', 'horarios.id')
            ->select('unidades.*', 'horarios.horario')
            ->get();


        return view('admin.unidade.index', compact('unidades', 'horarios'));
    }

    public function create()
    {
        $horarios = Horario::get();
        $horario = '';
        return view('admin.unidade.create', ['unidade' => new Unidade()], compact('horarios','horario'));
    }



    public function store(UnidadeValidationFormRequest $request)
    {

        $data = $request->all();
        unset($data['horario']);
        $data['horario_id'] = $request->horario;


        $response = Unidade::create($data);



        if ($response) {
            Alert::success('', 'Sucesso!');
            return redirect('admin/unidades');

        } else {
            Alert::error('', 'Erro!');
            return redirect('admin/unidades');
        }


    }

    public function show($id)
    {
        $unidade = Unidade::findOrFail($id);

              

        return view('admin.unidade.show', compact('unidade'));
    }

    public function edit($id)
    {
        $unidade = Unidade::findOrFail($id);
        $horarios = Horario::get()->where('id', '<>', $unidade->horario_id);
        $horario = Horario::findOrFail($unidade->horario_id);


        return view('admin.unidade.edit', compact('unidade', 'horarios', 'horario'));
    }



    public function update(UnidadeValidationFormRequest $request, $id)
    {

        $unidade = Unidade::findOrFail($id);

        $data = $request->all();

        unset($data['horario']);

        $data['horario_id'] = $request->horario;        

        $unidade->fill($data);

        $response = $unidade->save();


        if ($response) {

            Alert::success('', 'Sucesso!');
            return redirect('admin/unidades/' . $unidade->id);

        } else {
            Alert::error('', 'Erro!');
            return redirect('admin/unidades' . $unidade->id);
        }

    }

    public function destroy($id)
    {
        $unidade = Unidade::find($id);
        if (!$unidade) {
            abort(404);
        }

        $response = $unidade->delete();

        return redirect()
            ->route('unidades.index')
            ->with('success', 'Unidade excluída com Sucesso!');


        return redirect()
            ->route('unidades.index')
            ->with('error', 'Erro ao Excluir a Unidade!');


    }
}

resources/views/admin/unidade/_form.blade.php
                
@php
$horario = $unidade->horario;
@endphp 
 

{!!csrf_field()!!}

<input type="hidden" name="id" value="{{$unidade->id}}">

<div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" id="nome" name="nome" value="{{old('nome',$unidade->nome)}}" >
</div>

<div class="form-group">
    <label for="telefone">telefone</label>
    <input type="text" class="form-control" id="telefone" name="telefone" value="{{old('telefone',$unidade->telefone)}}">
</div>

<div class="form-group">
    <label for="email">E-mail</label>
    <input type="email" class="form-control" id="email" name="email" value="{{old('email',$unidade->email)}}">
</div>

<div class="form-group">
    <label for="horario">Horário de Funcionamento</label>
    <select class="form-control" name="horario" id="horario">
        @if($horario)
        <option value="{{ $horario->id }}">{{ $horario->horario }}</option>
        
        @else
        <option value="">Selecione</option>
        @endif

        @foreach($horarios as $horario)
        <option value="{{ $horario->id }}" {{old('horario',$horario->horario) == $horario->id ?'selected="selected"': ''}}>{{ $horario->horario }}</option>
        @endforeach

    </select>
</div>

<div class="form-group">
    <label for="localizacao">Localização</label>
    <input type="text" class="form-control" id="localizacao" name="localizacao" value="{{old('localizacao',$unidade->localizacao)}}" placeholder="Iframe de Localização">
    <p>Observação: <code>Deve ser obtido no google maps o iframe com o código da localização no tamanho "Médio".</code></p>
</div>

resources/views/admin/unidade/create.blade.php
@extends('admin.layouts.app')


@section('content')

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Nova Unidade</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('unidades.index') }}">Unidades</a></li>
                    <li class="breadcrumb-item active">Nova Unidade</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>

@include('admin.includes.alerts')

<section class="content">
    <div class="row">
        <div class="col-12">        
            <div class="card">              
                <div class="card-body">
                    <form role="form" method="POST" action="{{ route('unidades.store')}}">                     
                        @include('admin.unidade._form')                           
                        <button type="submit" class="btn btn-success">Cadastrar</button>   
                    </form>
                </div>
            </div>          
        </div>       
    </div>     
</section>

@endsection

resources/views/admin/unidade/edit.blade.php
@extends('admin.layouts.app')


@section('content')

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar Unidade</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('unidades.index') }}">Unidades</a></li>  
                    <li class="breadcrumb-item"><a href="{{ route('unidades.show',$unidade->id) }}">Informações da Unidades</a></li>              
                    <li class="breadcrumb-item active">Editar Unidade</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>

@include('admin.includes.alerts')

<section class="content">
    <div class="row">
        <div class="col-12">        
            <div class="card">              
                <div class="card-body">
                    <form role="form" method="POST" action="{{ route('unidades.update', $unidade->id)}}">
                        {{method_field('PUT')}}
                        @include('admin.unidade._form')                           
                        <button type="submit" class="btn btn-success">Editar</button>   
                    </form>
                </div>
            </div>          
        </div>       
    </div>     
</section>

@endsection

resources/views/admin/unidade/index.blade.php
@extends('admin.layouts.app')


@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Unidades IDJ</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
                    <li class="breadcrumb-item active">Unidades</li>
                </ol>
            </div>
        </div>
    </div>
</section>

@include('admin.includes.alerts')
@include('sweet::alert')

<section class="content">
    <div class="row">
        <div class="col-12">        
            <div class="card">

                <div class="card-body">
                    <a class="btn btn-outline-info float-left" href="{{route('unidades.create')}}" ><i class="fa fa-plus"></i> Novo</a>
                </div>

                <div class="card-body">
                    <table id="example1" class="table table-hover">
                        <thead>
                            <tr>
                                <th>Unidade</th>    
                                <th style="width: 60px">Ações</th>                                    
                            </tr>
                        </thead>
                        <tbody>   

                            @foreach($unidades as $unidade)

                            <tr>
                                <td>   
                                    <strong> {{ $unidade->nome }}</strong>
                                    <p class="text-muted">
                                        <span class="description">Telefones: {{ $unidade->email }} | E-mail: {{ $unidade->email }}</span>
                                    </p>                   
                                </td>

                                <td>
                                    <a class="btn btn-outline-info" href="{{route('unidades.show',$unidade->id)}}"><i class="fa fa-eye"></i></a>
                                </td>                                                     
                            </tr>  


                            @endforeach           

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Descrição da Unidade</th>    
                                <th style="width: 60px">Ações</th>                                     
                            </tr>
                        </tfoot>
                    </table>
                </div>         
            </div>          
        </div>        
    </div>      
</section>

@endsection

resources/views/admin/unidade/show.blade.php
 
@extends('admin.layouts.app')


@section('content')

@php
$horario = $unidade->horario;

@endphp

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Informações da Unidade</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('unidades.index') }}">Unidades</a></li>
                    <li class="breadcrumb-item active">Informações da Unidade</li>
                </ol>
            </div>
        </div>
    </div>
</section>
@include('sweet::alert')

<section class="content">
    <div class="container-fluid">
        
        <div class="row">


            <div class="col-md-12">
                <div class="card card-widget widget-user">     
                    <div class="widget-user-header text-white" style="background: url('../../dist/img/photo1.png') center center;">                
                        <h5 class="widget-user-desc">{{ $unidade->nome }} </h5>

                        <button  class="btn btn-danger float-right" data-toggle="modal" data-target="#destroy{{ $unidade->id }}"><i class="fa fa-trash"></i> Excluir</button>
                        <a class="btn btn-info float-right" href="{{route('unidades.edit',$unidade->id)}}"><i class="fa fa-edit"></i>Editar</a>
                       
                    </div>

                    <div class="card-footer">

                        <div class="row">
                            <div class="col-sm-4 border-right">
                                <div class="description-block">
                                    <h5 class="description-header">Horário de Funcionamento</h5>                      
                                    <span class="tag tag-success">{{ $horario->horario }}</span>  
                                </div>              
                            </div> 

                            <div class="col-sm-4 border-right">
                                <div class="description-block">
                                    <h5 class="description-header">Telefones</h5>
                                    <span class="tag tag-success">{{ $unidade->telefone }}</span>  
                                </div>                
                            </div>

                            <div class="col-sm-4">
                                <div class="description-block">
                                    <h5 class="description-header">E-mail</h5>
                                    <span class="tag tag-success">{{ $unidade->email }}</span> 
                                </div>                  
                            </div> 

                        </div>
                    </div>
                </div>   
            </div>


            <div class="col-md-5">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Colaboradores</h3>
                    </div>

                    <div class="card-body">

                        <div class="user-block">
                            <img class="img-circle" src="{{ asset('../../dist/img/user1-128x128.jpg')}}" >
                            <span class="username"><a href="#">DTI</a></span>
                            <span class="description">Telefones: (85) 4012-0725 | E-mail: dti@idj.com.br</span> 
                        </div> 
                        <hr> 

                        <div class="user-block">
                            <img class="img-circle" src="{{ asset('../../dist/img/user1-128x128.jpg')}}" >
                            <span class="username"><a href="#">DTI</a></span>
                            <span class="description">Telefones: (85) 4012-0725 | E-mail: dti@idj.com.br</span> 
                        </div> 
                        <hr> 

                        <div class="user-block">
                            <img class="img-circle" src="{{ asset('../../dist/img/user1-128x128.jpg')}}" >
                            <span class="username"><a href="#">DTI</a></span>
                            <span class="description">Telefones: (85) 4012-0725 | E-mail: dti@idj.com.br</span> 
                        </div> 
                        <hr> 

                    </div>                    
                </div>
            </div>


            <div class="col-md-7">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Localização</h3>
                    </div>                   
                    <center>  
                        <?php echo $unidade->localizacao ?>
                    </center>                                
                </div>
            </div>




        </div>
</section>
@endsection