routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

$this->group([
              'middleware'  => ['auth'],
              'namespace'   =>  'Admin',
              'prefix'      =>  'admin' 
             ],function() { 


Route::resource('home', 'HomeController');
Route::resource('setores', 'SetorController');
Route::resource('unidades', 'UnidadeController');
Route::resource('horarios', 'HorarioController');


});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>


@include('admin.layouts.head')

@include('admin.layouts.menu')

<body class="hold-transition sidebar-mini">
        <div class="content-wrapper">  
        

        @yield('content')
        
        </div>
</body>



@include('admin.layouts.footer')
</html>

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
  <strong>Copyright &copy; 2002-2018 <a href="http://www.idj.com.br">Instituto Dom José de Educação e Cultura</a>.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 2.0
  </div>
</footer>  
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
</aside>


<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('plugins/fastclick/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('dist/js/demo.js') }}"></script>
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>

<script>

$(function () {
  $("#example1").DataTable();
  $('#example2').DataTable({
    "paging": true,
    "lengthChange": false,
    "searching": false,
    "ordering": true,
    "info": true,
    "autoWidth": false
  });
});



$(document).ready(function () {

  function limpa_cep() {
      // Limpa valores do formulário de cep.
      $("#logradouro").val("");
      $("#bairro").val("");
      $("#cidade").val("");
      $("#uf").val("");

  }

  //Quando o campo cep perde o foco.
  $("#cep").blur(function () {

      //Nova variável "cep" somente com dígitos.
      var cep = $(this).val().replace(/\D/g, '');

      //Verifica se campo cep possui valor informado.
      if (cep != "") {

          //Expressão regular para validar o CEP.
          var validacep = /^[0-9]{8}$/;

          //Valida o formato do CEP.
          if (validacep.test(cep)) {

              //Preenche os campos com "..." enquanto consulta webservice.
              $("#logradouro").val("Aguarde..");
              $("#bairro").val("Aguarde..");
              $("#cidade").val("Aguarde..");
              $("#uf").val("Aguarde..");


              //Consulta o webservice viacep.com.br/
              $.getJSON("//viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {

                  if (!("erro" in dados)) {
                      //Atualiza os campos com os valores da consulta.
                      $("#logradouro").val(dados.logradouro);
                      $("#bairro").val(dados.bairro);
                      $("#cidade").val(dados.localidade);
                      $("#uf").val(dados.uf);

                  } //end if.
                  else {
                      //CEP pesquisado não foi encontrado.
                      limpa_cep();
                      alert("CEP NÃO ENCONTRADO!");
                  }
              });
          } //end if.
          else {
              //cep é inválido.
              limpa_cep();
              alert("FORMATO DE CEP INVÁLIDO");
          }
      } //end if.
      else {
          //cep sem valor, limpa formulário.
          limpa_cep();
      }
  });

});

</script>

<script type="text/javascript">
  
  function CEP(cep) {

          if(cep.value.length == 5)
              cep.value = cep.value + '-';

  }


 function CPF(cpf) {

          if(cpf.value.length == 3)
              cpf.value = cpf.value + '.';

          if(cpf.value.length == 7)
              cpf.value = cpf.value + '.'; 

          if(cpf.value.length == 11)
              cpf.value = cpf.value + '-';


  }
  
  function Celular(celular) {

            
          if(celular.value.length == 0)                
                   celular.value = '(' + celular.value;          
          
          if(celular.value.length == 3)
                   celular.value = celular.value + ')';

          if(celular.value.length == 5)
                   celular.value = celular.value + ' ';  
   
          if(celular.value.length == 10)
                   celular.value = celular.value + '-';


  
  }

  function Telefone(telefone) {

        
      if(telefone.value.length == 0)                
               telefone.value = '(' + telefone.value;          
      
      if(telefone.value.length == 3)
               telefone.value = telefone.value + ')';
 
      if(telefone.value.length == 8)
               telefone.value = telefone.value + '-';


  
}

</script>

resources/views/admin/layouts/head.blade.php
<head>
    <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>INTRANET | {{strtoupper (Request::segment(2))}}</title>
      
      <!-- Tell the browser to be responsive to screen width -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      
      <!-- Font Awesome -->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
      <!-- Ionicons -->
      <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
      <!-- Theme style -->
      <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
      <!-- jvectormap -->
      <link rel="stylesheet" href="{{ asset('plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
      <!-- Date Picker -->
      <link rel="stylesheet" href="{{ asset('plugins/datepicker/datepicker3.css') }}">
      <!-- Daterange picker -->
      <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker-bs3.css') }}">
      <!-- bootstrap wysihtml5 - text editor -->
      <link rel="stylesheet" href="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
      <!-- Google Font: Source Sans Pro -->
      <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">  
     <link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
     <!-- SweetAlert -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css"  > 
     <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>  
    
       
    </head>

resources/views/admin/layouts/menu.blade.php
 
  <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
    
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
      </li>     
    </ul>
  </nav>

  <aside class="main-sidebar sidebar-dark-primary elevation-4">
  
    <a href="#" class="brand-link">
      <img src="{{ asset('dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Ragnar</span>
    </a>

    <div class="sidebar">
    
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="perfil.html" class="d-block">{{ auth()->user()->name }}</a>
        </div>
      </div>
      
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">         
          <li class="nav-item">            
            <a href="{{route('home.index')}}" {!! Request::segment(2) == 'home' ? 'class="nav-link active"' : 'class="nav-link"' !!}>
              <i class="nav-icon fa fa-tachometer-alt"></i>
              <p>Home</p>
            </a>
          </li>          

        <li class="nav-header">ADMINISTRATIVO</li>
         
      
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-id-card"></i>
              <p>Colaboradores</p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{{route('unidades.index')}}" {!! Request::segment(2) == 'unidades' ? 'class="nav-link active"' : 'class="nav-link"' !!}>
              <i class="nav-icon fas fa-id-card"></i>
              <p>Unidades</p>
            </a>
          </li> 

          <li class="nav-item">
              <a href="{{route('setores.index')}}" {!! Request::segment(2) == 'setores' ? 'class="nav-link active"' : 'class="nav-link"' !!}>
                <i class="nav-icon fas fa-id-card"></i>
                <p>Setores</p>
              </a>
            </li>  
  
          <li class="nav-header">CONFIGURAÇÕES</li>
          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-cogs"></i>
              <p>Geral</p>
            </a>
          </li>

        </ul>
      </nav>  
    </div>
  
  </aside>