routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

$this->group([
              'middleware'  => ['auth'],
              'namespace'   =>  'Admin',
              'prefix'      =>  'admin' 
             ],function() { 


Route::resource('home', 'HomeController');
Route::resource('setores', 'SetorController');
Route::resource('unidades', 'UnidadeController');
Route::resource('horarios', 'HorarioController');


});

app/Models/Admin/Horario.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use DB;


class Horario extends Model {

    protected $fillable = ['horario'];
    protected $guarded = ['id', 'created_at', 'update_at'];

    public function Unidade(){

        return $this->belongsTo(Unidade::class);
    }
  
}

app/Http/Controllers/Admin/HorarioController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Admin\Horario;
use App\Http\Controllers\Controller;

class HorarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        

        $horarios = Horario::get();
         

        return view('horario.index', compact('horarios'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
       
        $horario = New Horario();
        $horario->operation = $request->operation;       
        $response = $horario->save();
                

           if($response)       
             
            
             return redirect ()
            ->route('horarios.index')
             ->with('success','Horário salvo com sucesso!');
            
        
            return redirect()
             ->route('horarios.index')
             ->with('error','Erro ao salvar o horário!');
            
    

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


    
         $horario = Horario::findOrFail($id);

         $horario->operation = $request->operation;

         $response = $horario->save();
       
         if($response)
        
             
            
             return redirect ()
            ->route('horarios.index')
             ->with('success','Sucesso ao Editar!');
            
        
            return redirect()
             ->route('horarios.index')
             ->with('error','Erro ao Editar!');
        
    

    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $horario = Horario::find($id);
        if(!$horario){
            abort(404);
        }

       $response = $horario->delete();

         return redirect ()
            ->route('horarios.index')
             ->with('success','Horário excluído com Sucesso!');
            
        
            return redirect()
             ->route('horarios.index')
             ->with('error','Erro ao Excluir o Horário!');
        
    
    }
}

resources/views/admin/horario/index.blade.php
@extends('layouts.app')

@extends('layouts.menu')

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Horários IDJ</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home')}}">Home</a></li>
                    <li class="breadcrumb-item active">Horários</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
@include('includes.alerts')
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12"> 

            <div class="card">

                @include('horario.modal-form-add')


                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-hover"">
                        <thead>
                            <tr>
                                <th>Descrição dos Horários</th> 
                                <th>Ações</th>                                        
                            </tr>
                        </thead>
                        <tbody>   

                            @foreach($horarios as $horario)

                            <tr>
                                <td>                     
                                    <i class="nav-icon fas fa-clock"></i> 
                                    <span class="username">{{ $horario->operation }}</span>                   

                                </td>

                                <td>  

                                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modal-edit-{{ $horario->id }}"><i class="fa fa-edit"></i></button> 

                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-trash-{{ $horario->id }}"><i class="fa fa-trash"></i></button> 

                                </td>                                                     
                            </tr>  

                            @include('horario.modal-form-options')

                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Descrição dos Horários</th>
                                <th>Ações</th>                                  
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>

@endsection

resources/views/admin/horario/modal-form-add.blade.php
 <div class="card-body">

                <button type="button" class="btn btn-primary btn-plus" data-toggle="modal" data-target="#modal-default"><i class="fa fa-plus"></i> Adiconar Horário</button> 

                    
  <div class="modal fade" id="modal-default">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            
            <div class="modal-header">
              <h4>Adicione um Novo Horário</h4>                              
            </div>
            
            <div class="modal-body">
              <form role="form" method="POST" action="{{ route('horarios.store')}}">
                
                {!!csrf_field()!!}

                <div class="card-body">
                  <div class="form-group">
                    <label for="operation">Descrição</label>
                    <input type="text" class="form-control" id="operation" name="operation" placeholder="Horário">
                  </div>                      
                  <button type="submit" class="btn btn-success">Salvar</button> 
                  <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                         
              </form>
            </div>

            
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
  </div>
  <!-- /.modal -->


            
</div>  

resources/views/admin/horario/modal-form-options.blade.php
  

                




      <div class="modal fade" id="modal-trash-{{ $horario->id }}">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                
                <div class="modal-header">
                  <h4>Cuidado!</h4>                              
                </div>
                
                <div class="modal-body">
                  <form role="form" method="POST" action="{{ route('horarios.destroy', $horario->id)}}">
                      
                      {!!csrf_field()!!}

                <center>
                    <h2>Tem certeza que quer excluir o horário?</h2>
                    <h3>"{{ $horario->operation }}"</h3>
                    <br>
                    <hr>
                </center> 
                      
                      <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                      <button type="submit" class="btn btn-danger">Excluir</button>              
                  </form>
                </div>
                
              </div>         
            </div>        
      </div>
      
                                        
      <div class="modal fade" id="modal-edit-{{ $horario->id }}">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">            
                <div class="modal-header">
                  <h4>Editar Horário</h4>                              
                </div>
                
                <div class="modal-body">
                  <form role="form"  action="{{ route('horarios.update', $horario->id)}}" method="post">
             
                    
                    {!!csrf_field()!!}

                    <div class="card-body">
                      <div class="form-group">
                        <label for="operation">Descrição</label>
                        <input type="text" class="form-control" id="operation" name="operation" placeholder="Horário" value="{{ $horario->operation }}">
                      </div>    
                      
                      <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                      <button type="submit" class="btn btn-success">Alterar</button>              
                  </form>
                </div>            
              </div>         
            </div>        
      </div>