routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

$this->group([
              'middleware'  => ['auth'],
              'namespace'   =>  'Admin',
              'prefix'      =>  'admin' 
             ],function() { 


Route::resource('home', 'HomeController');
Route::resource('setores', 'SetorController');
Route::resource('unidades', 'UnidadeController');
Route::resource('horarios', 'HorarioController');


});

app/Models/Admin/Setor.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use App\Models\Admin\Horario;
use App\Models\Admin\Unidade;
use App\Models\Admin\Instruction;

class Setor extends Model
{
     protected $fillable = [
        'nome', 'telefone','email','unidade_id'
    ];



	

    public function unidade(){

      return $this->hasOne(Unidade::class);
    }



    public function instruction(){

      return $this->hasMany(Instruction::class);
    }


  


}

app/Http/Controllers/Admin/SetorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\Admin\Setor;
use App\Models\Admin\Unidade;
use App\Models\Admin\Instruction;
use App\Http\Controllers\Controller;
use App\Http\Requests\SetorValidationFormRequest;
use DB;
use Alert;


class SetorController extends Controller
{
    public function index()
    {


        $setores = Setor::get();


        return view('admin.setor.index', compact('setores'));
    }

    public function create()
    {
       // $setores = Setor::get();
        $unidades = Unidade::get();
        $unidade = '';
        
        return view('admin.setor.create', ['setor' => new Setor()], compact('unidades','unidade'));
    }



    public function store(SetorValidationFormRequest $request)
    {

        $data = $request->all();
        unset($data['unidade']);
        $data['unidade_id'] = $request->unidade;


        $response = Setor::create($data);



        if ($response) {
            Alert::success('', 'Sucesso!');
            return redirect('admin/setores');

        } else {
            Alert::error('', 'Erro!');
            return redirect('admin/setores');
        }



    }

    public function show($id)
    {
        $setor = Setor::findOrFail($id);
        $instructions =  $setor->instruction;
                      

        return view('admin.setor.show', compact('setor','instructions'));
    }


    public function edit($id)
    {
        $setor = Setor::findOrFail($id);
        $unidades = Unidade::get()->where('id', '<>', $setor->unidade_id);
        $unidade = Unidade::findOrFail($setor->unidade_id);


        return view('admin.setor.edit', compact('setor', 'unidades','unidade'));
    }



    public function update(Request $request, $id)
    {


        $setor = Setor::findOrFail($id);

        $data = $request->all();

        unset($data['unidade']);

        $data['horario_id'] = $request->unidade;        

        $setor->fill($data);

        $response = $setor->save();


        if ($response) {

            Alert::success('', 'Sucesso!');
            return redirect('admin/setores/' . $setor->id);

        } else {
            Alert::error('', 'Erro!');
            return redirect('admin/setores' . $setor->id);
        }


    }

    public function destroy($id)
    {
        $setor = Setor::find($id);
        if (!$setor) {
            abort(404);
        }

        $response = $setor->delete();

        return redirect()
            ->route('setores.index')
            ->with('success', 'Setor excluído com Sucesso!');


        return redirect()
            ->route('setores.index')
            ->with('error', 'Erro ao Excluir o Setor!');


    }



}

resources/views/admin/setor/_form.blade.php
                
@php

if($unidade){
$unidade = $unidade;
}
else {
    $unidade = '';
}

@endphp 

{!!csrf_field()!!}

<input type="hidden" name="id" value="{{$setor->id}}">


<div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" id="nome" name="nome" value="{{old('nome',$setor->nome)}}">
</div>

<div class="form-group">
    <label for="telefone">Telefones</label>
    <input type="text" class="form-control" id="telefone" name="telefone" value="{{old('telefone',$setor->telefone)}}">
</div>

<div class="form-group">
    <label for="email">E-mail</label>
    <input type="email" class="form-control" id="email" name="email" value="{{old('email',$setor->email)}}">
</div>


<div class="form-group">
        <label for="unidade">Unidade</label>
        <select class="form-control" name="unidade" id="unidade">          
            
            @if($unidade)
            <option value="{{ $unidade->id }}">{{ $unidade->nome }}</option>
            
            @else
            <option value="">Selecione</option>
            @endif

            @foreach($unidades as $unidade)
            <option value="{{ $unidade->id }}" {{old('unidade',$unidade->nome) == $unidade->id ?'selected="selected"': ''}}>{{ $unidade->nome }}</option>
            @endforeach
    
        </select>
    </div>

resources/views/admin/setor/create.blade.php
@extends('admin.layouts.app')


@section('content')


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Novo Setor</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('setores.index') }}">Setores</a></li>
                    <li class="breadcrumb-item active">Novo Setor</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>

@include('admin.includes.alerts')

<section class="content">
    <div class="row">
        <div class="col-12">        
            <div class="card">              
                <div class="card-body">
                    <form role="form" method="POST" action="{{ route('setores.store')}}">                     
                        @include('admin.setor._form')                           
                        <button type="submit" class="btn btn-success">Cadastrar</button>   
                    </form>
                </div>
            </div>          
        </div>       
    </div>     
</section>

@endsection

resources/views/admin/setor/edit.blade.php
@extends('admin.layouts.app')


@section('content')

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar Setor</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('setores.index') }}">Setores</a></li>  
                    <li class="breadcrumb-item"><a href="{{ route('setores.show',$setor->id) }}">Informações do Setor</a></li>              
                    <li class="breadcrumb-item active">Editar Setor</a></li>
                </ol>
            </div>
        </div>
    </div>
</section>

@include('admin.includes.alerts')

<section class="content">
    <div class="row">
        <div class="col-12">        
            <div class="card">              
                <div class="card-body">
                    <form role="form" method="POST" action="{{ route('setores.update', $setor->id)}}">
                        {{method_field('PUT')}}
                        @include('admin.setor._form')                           
                        <button type="submit" class="btn btn-success">Editar</button>   
                    </form>
                </div>
            </div>          
        </div>       
    </div>     
</section>

@endsection

resources/views/admin/setor/index.blade.php
@extends('admin.layouts.app')



@section('content')

<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Setores IDJ</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
              <li class="breadcrumb-item active">Setores</li>
            </ol>
          </div>
        </div>
      </div>
</section>


@include('sweet::alert')
  
    <section class="content">
      <div class="row">
        <div class="col-12">        
          <div class="card">
            
              <div class="card-body">
                  <a class="btn btn-outline-info float-left" href="{{route('setores.create')}}" ><i class="fa fa-plus"></i> Novo</a>
              </div>
                        
            <div class="card-body">
              <table id="example1" class="table table-hover">
                <thead>
                <tr>
                  <th>Setor</th>
                  <th style="width: 60px">Ações</th>                                        
                </tr>
                </thead>

                  <tbody>   

                     @foreach($setores as $setor)

                     <tr>
                        <td>   
                            <strong> {{ $setor->nome }}</strong>
                            <p class="text-muted">
                                <span class="description">Telefones: {{ $setor->email }} | E-mail: {{ $setor->email }}</span>
                            </p>                   
                        </td>

                        <td>
                            <a class="btn btn-outline-info" href="{{route('setores.show',$setor->id)}}"><i class="fa fa-eye"></i></a>
                        </td>                                                     
                    </tr>

                           
                    @endforeach           

                </tbody>

                <tfoot>

                    <tr>
                      <th>Setor</th>
                      <th>Ações</th>                                    
                    </tr style="width: 60px">

                </tfoot>

              </table>
            </div>          
          </div>         
        </div>      
      </div>      
    </section>



@endsection

resources/views/admin/setor/setor-info.blade.php
 
@extends('admin.layouts.app')


@section('content')

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Informações do Setor</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('setores.index') }}">Setores</a></li>
                    <li class="breadcrumb-item active">Informações do Setor</li>
                </ol>
            </div>
        </div>
    </div>
</section>



<section class="content">      
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="card card-primary ">
                    <div class="card-header">
                        <h3 class="card-title">{{ $setor->name }}</h3>
                    </div>
                    <div class="card-body box-profile">     
                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                @foreach($instructions as $instruction)
                                <p>
                                    <a href="<?php echo $instruction->link ?>" target="_bank"><b><?php echo $instruction->descricao ?></b></a>
                                    <a href="#" class="btn btn-info btn-sm float-right"  data-toggle="modal" data-target="#modal-edit-{{ $instruction->id }}"><i class="fa fa-edit"></i></a>
                                    <a href="#" class="btn btn-danger btn-sm float-right" data-toggle="modal" data-target="#modal-trash-{{ $instruction->id }}"><i class="fa fa-trash"></i></a> 
                                </p>
                                
                               
                                @endforeach                                         
                            </li>                       
                        </ul>
                        <a href="#" class="btn btn-primary btn-block" data-toggle="modal" data-target="#modal-default"><b><i class="fa fa-plus">&nbsp IT</i></b></a> 
                        <div class="modal fade" id="modal-default">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">            
                                    <div class="modal-header">
                                        <h4>Adicione uma Nova IT</h4>                              
                                    </div>            
                                    <div class="modal-body">
                                        <form role="form" method="POST" action="#">
                                            {!!csrf_field()!!}
                                            <div class="card-body">
                                                <div class="form-group">
                                                    <input type="hidden" name="setor_id" value="{{ $setor->id }}">  
                                                    <label for="descricao">Nome</label>
                                                    <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Descrição da IT">
                                                </div>
                                                <div class="form-group">
                                                    <label for="link">Link</label>
                                                    <input type="text" class="form-control" id="link" name="link" placeholder="Link da IT">
                                                </div>       
                                                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                                                <button type="submit" class="btn btn-success">Salvar</button>   
                                        </form>
                                    </div>
                                </div>       
                            </div>        
                        </div>    
                    </div>
                </div>    
            </div>
        </div>

        <div class="col-md-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Sobre o Setor</h3>
                </div>                    
                <div class="card-body">                                     
                    <strong><i class="fa fa-pencil mr-1"></i> Contatos</strong>
                    <p class="text-muted">
                        <span class="tag tag-danger">{{ $setor->email }}</span>
                        <span class="tag tag-success"> | </span> 
                        <span class="tag tag-success">{{ $setor->phone }}</span>                        
                    </p>
                    <hr>
                    <strong><i class="fa fa-book mr-1"></i> Supervisor</strong>
                    <p class="text-muted">
                        rayan.carvalho@idj.com.br | (85) 4012-0743
                    </p>
                    <hr>
                    <strong><i class="fa fa-book mr-1"></i> Funcionamento</strong>
                    <p class="text-muted">
                        rayan.carvalho@idj.com.br | (85) 4012-0743
                    </p>
                    <hr>
                </div>              
            </div>
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Colaboradores</h3>
                </div>                   
                <div class="card-body">
                    <strong><i class="fa fa-book mr-1"></i><a href=""> Rayan Carvalho</a></strong>
                    <p class="text-muted">
                        rayan.carvalho@idj.com.br | (85) 4012-0743
                    </p>
                    <hr>
                    <strong><i class="fa fa-book mr-1"></i><a href=""> Rayan Carvalho</a></strong>
                    <p class="text-muted">
                        rayan.carvalho@idj.com.br | (85) 4012-0743
                    </p>
                    <hr>
                </div>                    
            </div>              
        </div>        
    </div>
</div>      
</section>
@endsection

resources/views/admin/setor/show.blade.php
@extends('admin.layouts.app')



@section('content')

<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ $setor->nome }}</h1>
            <br>
          </div>

          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home.index') }}">Home</a></li>
              <li class="breadcrumb-item"><a href="{{ route('setores.index') }}">Setores</a></li>
              <li class="breadcrumb-item active">Sobre o Setor</li>
            </ol>
          </div>

          <div class="col-md-4">
            <a class="btn btn-outline-info float-left" href="{{route('setores.edit',$setor->id)}}"><i class="fa fa-edit"></i>Editar</a>
            <button  class="btn btn-outline-danger float-left" data-toggle="modal" data-target="#"><i class="fa fa-trash"></i> Excluir</button>
          </div>

        </div>
      </div>
</section>


@include('sweet::alert')
  
<section class="content">      
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                    <div class="card card-primary ">
                        <div class="card-header">
                            <h3 class="card-title"> Instruções de Trabalho</h3>
                        </div>
                        <div class="card-body box-profile">   
                   
                            <ul class="list-group list-group-unbordered mb-3">
                                <li class="list-group-item">
                                    
                                    @foreach($instructions as $instruction)
                                    <p>
                                        <a href="<?php echo $instruction->link ?>" target="_bank"><b><?php echo $instruction->descricao ?></b></a>
                                        <a href="#" class="btn btn-info btn-sm float-right"  data-toggle="modal" data-target="#modal-edit-{{ $instruction->id }}"><i class="fa fa-edit"></i></a>
                                        <a href="#" class="btn btn-danger btn-sm float-right" data-toggle="modal" data-target="#modal-trash-{{ $instruction->id }}"><i class="fa fa-trash"></i></a> 
                                    </p>
                                    
                                   
                                    @endforeach                                         
                                </li>                       
                            </ul>
                            <a href="#" class="btn btn-primary btn-block" data-toggle="modal" data-target="#modal-default"><b><i class="fa fa-plus">&nbsp IT</i></b></a> 
                            <div class="modal fade" id="modal-default">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">            
                                        <div class="modal-header">
                                            <h4>Adicione uma Nova IT</h4>                              
                                        </div>            
                                        <div class="modal-body">
                                            <form role="form" method="POST" action="#">
                                                {!!csrf_field()!!}
                                                <div class="card-body">
                                                    <div class="form-group">
                                                        <input type="hidden" name="setor_id" value="{{ $setor->id }}">  
                                                        <label for="descricao">Nome</label>
                                                        <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Descrição da IT">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="link">Link</label>
                                                        <input type="text" class="form-control" id="link" name="link" placeholder="Link da IT">
                                                    </div>       
                                                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                                                    <button type="submit" class="btn btn-success">Salvar</button>   
                                            </form>
                                        </div>
                                    </div>       
                                </div>        
                            </div>    
                        </div>
                    </div>    
                </div>
            </div>
    
            <div class="col-md-8">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Sobre</h3>
                    </div>                    
                    <div class="card-body">                                     
                        <strong><i class="fa fa-pencil mr-1"></i> Contatos</strong>
                        <p class="text-muted">
                            <span class="tag tag-danger">{{ $setor->email }}</span>
                            <span class="tag tag-success"> | </span> 
                            <span class="tag tag-success">{{ $setor->telefone }}</span>                        
                        </p>
                        <hr>
                        <strong><i class="fa fa-book mr-1"></i> Supervisor</strong>
                        <p class="text-muted">
                            rayan.carvalho@idj.com.br | (85) 4012-0743
                        </p>
                        <hr>
                        <strong><i class="fa fa-book mr-1"></i> Funcionamento</strong>
                        <p class="text-muted">
                            rayan.carvalho@idj.com.br | (85) 4012-0743
                        </p>
                        <hr>
                    </div>              
                </div>
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Colaboradores</h3>
                    </div>                   
                    <div class="card-body">
                        <strong><i class="fa fa-book mr-1"></i><a href=""> Rayan Carvalho</a></strong>
                        <p class="text-muted">
                            rayan.carvalho@idj.com.br | (85) 4012-0743
                        </p>
                        <hr>
                        <strong><i class="fa fa-book mr-1"></i><a href=""> Rayan Carvalho</a></strong>
                        <p class="text-muted">
                            rayan.carvalho@idj.com.br | (85) 4012-0743
                        </p>
                        <hr>
                    </div>                    
                </div>              
            </div>        
        </div>
    </div>      
</section>


@endsection